language: java
jdk:
  - openjdk8
before_install: 
  - sudo apt-get install ant
  - sudo apt-get install npm
script:
  - ant clean dist junit jacoco
before_deploy:
  - npm install netlify-cli -g
deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./report
  skip_cleanup: true